language: php

php:
  - 7.3
  - 7.4
  - hhvm

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - sed -i '/printerClass/d' phpunit.xml
  - echo "${TRAVIS_PHP_VERSION:0:3}"
  - if [[ "${TRAVIS_PHP_VERSION:0:3}" == "7.1" ]]; then sed -i 's/\(testbench.\+\?\)4.1/\13.8/g' composer.json; sed -i 's/\(phpunit.\+\?\)8.0/\17.5/g' composer.json; fi
  - cat composer.json
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
