<?php

namespace Turahe\Counters\Models;

use Illuminate\Database\Eloquent\Relations\Pivot;

class Counterable extends Pivot
{
    /**
     * @var string[]
     */
    protected $fillable = [
        'value',
        'counter_id',
        'counterable_id',
        'counterable_type',
    ];

    public function getTable()
    {
        return config('counter.models.table_pivot_name') ?: parent::getTable(); // TODO: Change the autogenerated stub
    }

    public function counter()
    {
        return $this->belongsTo(Counter::class, 'counter_id');
    }
}
